// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Dec 25 21:50:40 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef WXFRONTEND_H
#define WXFRONTEND_H


// begin wxGlade: ::extracode
// end wxGlade


#endif // WXFRONTEND_H
